[project]
name = "alexnet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.6",
    "torch>=2.7.0",
]

[dependency-groups]
dev = [
    "torchinfo>=1.8.0",
]
